models:
  speaker_embedding: models:/Speaker_Embedding_v1/latest
  #tt2: models:/Tacotron_2/latest
  tt2: models:/Tacotron_2_Test/latest

mel:
  sample_rate: 22050
  hop_length_ms: 12.5
  win_length_ms: 50
  n_mels: 80
  window_function: 'hann'

inverse_mel: 
  sample_rate: 22050
  hop_length_ms: 12.5
  win_length_ms: 50
  window_function: 'hann'

train:
  char_values: "abcdefghijklmnopqrstuvwxyz1234567890 "