mel:
  sample_rate: 16000
  hop_length_ms: 10
  win_length_ms: 25 
  n_mels: 80

clip:
  t: 160

meta:
  mlflow_remote_tracking: false
  cuda_gpu: 1

train:
  epochs: 1000
  learning_rate: 0.01
  eps: 0.0001
  N_speakers: 64
  M_utterances: 10
  shuffle: true
  root_dir: ../../../../media/overlord/My Passport
  source: local_directory
  repos: 
    LibriTTS:
      version: train-other-500

model:
  input_size: 80
  hidden_size: 257
  projection_size: 256
  embedding_size: 256
  num_layers: 3
  batch_size: 60
