mel:
  sample_rate: 22050
  hop_length_ms: 12.5
  win_length_ms: 50
  n_mels: 80
  window_function: 'hann'

transforms:
  char_values: "He lokdmavrfbutins,ghywcp;.WTIqDFGPx:EB-CARSMONLzjV\"?J91872U'()!K[]YZ3/4056XQ"
  
train:
  epochs: 1
  source: local_directory
  root_dir: data
  shuffle: true
  beta_0: 0.9
  beta_1: 0.999
  eps: 0.000001
  lr_max: 0.001
  lr_min: 0.00001
  decay_iterations: 50000
  l2_reg_weight: 0.000001
  repos:
    LibriTTS:
      version: dev-other

model:
  embedding_size: 512
  num_layers: [3, 2, 2, 5]
  encoder_conv_kernel_size: 5
  lstm_hidden_size: 256
  attn_hidden_size: 128
  attn_inverse_temperature: 1.0
  attn_window_length: 8
  attn_n_filters: 32
  attn_conv_kernel_size: 31
  batch_size: 6
  speaker_embedding_model_uri: models:/Speaker_Embedding_Test1/latest

meta: 
  mlflow_remote_tracking: false
