mel:
  sample_rate: 22050
  hop_length_ms: 12.5
  win_length_ms: 50
  n_mels: 80
  window_function: 'hann'

transforms:
  char_values: "He lokdmavrfbutins,ghywcp;.WTIqDFGPx:EB-CARSMONLzjV\"?J91872U'()!K[]YZ3/4056XQ"
  
train:
  epochs: 4
  source: local_directory
  root_dir: data
  shuffle: true
  beta_0: 0.9
  beta_1: 0.999
  eps: 0.000001
  lr_max: 0.001
  lr_min: 0.00001
  decay_iterations: 50000
  l2_reg_weight: 0.000001
  repos:
    LibriTTS:
      version: dev-other
  stop_token_threshold: 0.5

speaker_embedding_model:
  config_path: 'config/speaker_recog_encoder_dev.yml'
  state_dict_uri: 'mlruns/622292915956719578/5cde163e56ee472eb8b1f4bcc4a10b38/artifacts/state_dict'

model:
  speaker_embedding_model_uri: models:/Speaker_Embedding_Test1/latest
  embedding_size: 512
  speaker_embedding_size: 256
  num_layers: [3, 2, 5]
  encoder_conv_kernel_size: 5
  lstm_hidden_size: 256
  prenet_hidden_size: 256
  encoder_lstm_hidden_size: 1024
  location_hidden_dim: 128
  location_n_filters: 32
  location_kernel_size: 31
  attn_inverse_temperature: 1.0
  decoder_lstm_hidden_size: 1024
  postnet_embedding_dim: 512
  postnet_kernel_size: 5
  batch_size: 6

meta: 
  mlflow_remote_tracking: false
  cuda_gpu: 0
